# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Jaime Gutiérrez"                                # Your name
  description: "Periodista de datos"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    title: "<big><big><b style='color:#478079;'>Jaime</b><span style='#000000;'>Gutiérrez</span></big></big>"
    # logo: /img/logo.png
    background: white
    foreground: dark
    
    # your sub-pages
    left:
      - text: "<b>Contacto</b>"
        href: contacto/index.qmd
      - text: "<b>Sobre mí</b>"
        menu:
        - text: "Quién soy"
          href: sobre-mi/index.qmd
        - text: "CV"
          href: cv/jaime_gutierrez.qmd
      - text: "<b>Formación</b>"
        menu:
        - text: "Cursos"
          href: formacion/clases/index.qmd
        - text: "Ejericicios"
          href: formacion/ejercicios/index.qmd
    
    # your social media handles
    right:
      # - icon: folder-symlink
      #   href: https://github.com/jaimegutierrezh
      # - icon: twitter
      #   href: https://twitter.com/JaimeGutierrezH
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/jaimegutierrezh/
      - icon: envelope
        aria-label: email
        href: "mailto:jaime.gutierrezhernandez@gmail.com"  

# Botones
    button:   
    background-color: #478079; /* Green */
      color: white;
  

# Don't touch unless you know what you are doing :) ------------
  # search: 
  #   location: navbar
  #   type: textbox
  page-footer: 
    left: |
      <span class="faux-block"> <svg aria-hidden="true" role="img" viewBox="0 0 496 512" style="height:1em;width:0.97em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:white;overflow:visible;position:relative;"><path d="M245.83 214.87l-33.22 17.28c-9.43-19.58-25.24-19.93-27.46-19.93-22.13 0-33.22 14.61-33.22 43.84 0 23.57 9.21 43.84 33.22 43.84 14.47 0 24.65-7.09 30.57-21.26l30.55 15.5c-6.17 11.51-25.69 38.98-65.1 38.98-22.6 0-73.96-10.32-73.96-77.05 0-58.69 43-77.06 72.63-77.06 30.72-.01 52.7 11.95 65.99 35.86zm143.05 0l-32.78 17.28c-9.5-19.77-25.72-19.93-27.9-19.93-22.14 0-33.22 14.61-33.22 43.84 0 23.55 9.23 43.84 33.22 43.84 14.45 0 24.65-7.09 30.54-21.26l31 15.5c-2.1 3.75-21.39 38.98-65.09 38.98-22.69 0-73.96-9.87-73.96-77.05 0-58.67 42.97-77.06 72.63-77.06 30.71-.01 52.58 11.95 65.56 35.86zM247.56 8.05C104.74 8.05 0 123.11 0 256.05c0 138.49 113.6 248 247.56 248 129.93 0 248.44-100.87 248.44-248 0-137.87-106.62-248-248.44-248zm.87 450.81c-112.54 0-203.7-93.04-203.7-202.81 0-105.42 85.43-203.27 203.72-203.27 112.53 0 202.82 89.46 202.82 203.26-.01 121.69-99.68 202.82-202.84 202.82z"/></svg> 2023 Jaime Gutiérrez CC BY-SA 4.0</span>
    center: |
    right: |
      <span class="faux-block">Basada en la <a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">plantilla de Marvin Schmitt </a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true